name: LaravelPHPテスト

on:
  pull_request:
    branches: [main]

jobs:
  laravel_test:
    name: phpunit test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.19
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: app_test
      DB_USERNAME: root
      DB_PASSWORD: password

    steps:
      - uses: actions/checkout@v2
      - name: cache vendor
        id: cache
        uses: actions/cache@v1
        with:
          path: ./backend/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: run apt
        run: sudo apt update && sudo apt install git libicu-dev libonig-dev libzip-dev unzip locales python3-pip libmariadb-dev default-mysql-client python3-venv
      - name: run pip
        run: sudo pip3 install --upgrade pip && pip3 install python-dotenv mysqlclient ahocorapy && pip3 install -U ginza ja-ginza
      - name: Copy .env
        run: cd backend && php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: composer install
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd backend && composer install -n --prefer-dist
      - name: composer dump autoload
        run: cd backend && composer dump-autoload
      - name: generate key
        run: cd backend && php artisan key:generate --env=testing
      - name: migrate
        run: cd backend && php artisan migrate
      - name: unit test
        run: cd backend && ./vendor/bin/phpunit
